DOMAINS = [
    "my.bmi.ir",
    "cafebazaar.ir",
    "telewebion.com",
    "docs.google.com",
    "cdn.appsflyer.com",
    "varzesh3.com",
    "discord.com",
    "parsian-bank.ir",
    "snapp.ir",
    "oodi.zendesk.com",
    "cms.accuweather.com",
    "greenpepper.ir",
    "digikala.com",
    "blogfa.com",
    "cdn.medallia.com",
    "linkirani.ir",
    "speedtest.net",
    "google.com",
    "bqbank.ir",
    "roblox.com",
    "bki.ir",
    "zula.ir",
    "picofile.com",
    "yasdl.ir",
    "gsmarena.com",
    "uplod.ir",
    "ebank.bmi.ir",
    "myket.ir",
    "refah-bank.ir",
    "skyroom.online",
    "eset.com",
    "tgju.org",
    "sep.shaparak.ir",
    "digitalocean.com",
    "sale.alibaba.com",
    "xbox.com",
    "ilovepdf.com",
    "upsara.com",
    "bmi.ir",
    "yahoo.com",
    "soft98.ir",
    "alibaba.ir",
    "github.com",
    "moi.ir",
    "m.yandex.com",
    "ghbi.ir"
]

PORTS = [443, 2053, 2083, 2087, 2096, 8443]

IP_SOURCES = [
    "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/main/all/all_plain.txt",
    "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/main/all/all_plain_ipv4.txt"
]
